### ISSUE TITLE
Payment Open Bank Provider JSON mismate

### ISSUE THREAD

**Issue by jamesmcarthur115555** [customate/java-sdk#1]
```
@JsonProperty("results")
    private List<PaymentOpenBankingProvider> results;
```

I think this might need to be "items" and not results in PaymentOpenBankingProvider

**Comment by SBalac** [comment]
When I get the provider list using our API, I see "results" which matches the field name in the SDK:

{
    "results":  [
                    {
                        "provider_id":  "mock-payments-es-redirect",
                        "logo_url":  "https://truelayer-provider-assets.s3.amazonaws.com/global/logos/mock-payments-es-redirect.svg",
                        "icon_url":  "https://truelayer-provider-assets.s3.amazonaws.com/global/icons/mock-payments-es-redirect.svg",
                        "display_name":  "Mock Spain Payments â Redirect Flow",
                        "country":  "ES",
                        "single_immediate_payment_schemes":  [
                                                                 {
                                                                     "scheme_id":  "sepa_credit_transfer",
                                                                     "fee_options":  null,
                                                                     "requirements":  [
...

**Comment by jamesmcarthur115555** [comment]
The issue seemed to be the test system return ITEMS where live returns RESULTS - so when i raised this it was when we where using the sandbox - where as line live it is as per the SDK

I think the sandbox return needs updating so tests will pass

**Comment by SBalac** [comment]
As an API user when I call (Live) https://api.gocustomate.com/v1/open_banking_providers?currency=GBP&country=GB I get:
{
    "results":  [
                    {
                        "provider_id":  "oauth-starling",
...

When I call (Sandbox) https://sandbox-api.gocustomate.com/v1/open_banking_providers?currency=GBP&country=GB I get:{
    "results":  [
                    {
                        "provider_id":  "mock-payments-gb-redirect",
...

When I use our SDK in the Sandbox, I get:
{"results":[{"provider_id":"mock-payments-gb-redirect","logo_url":"https://truelayer-provider-assets.s3.amazonaws.com/uk/logos/mock-payments-gb-redirect.svg","icon_url":"https://truelayer-provider-assets.s3.amazonaws.com/uk/icons/mock-payments-gb-redirect.svg","display_name":"Mock UK Payments - Redirect Flow","country":"GB","single_immediate_payment_schemes":[{"scheme_id":"faster_payments_service","fee_options":null}]},{"provider_id":"ob-uki-mock-bank","logo_url":"","icon_url":"","display_name":"UKI Mock Bank","country":"GB","single_immediate_payment_schemes":[{"scheme_id":"faster_payments_service","fee_options":null}]}]}

And the definition for the SDK class is:

public class PaymentOpenBankingProviderPage extends BaseModel {
    @JsonProperty("results")
    private List<PaymentOpenBankingProvider> results;

**Comment by SBalac** [comment]
Shown not to be an issue.

**Comment by jamesmcarthur115555** [comment]
[stdout] Running Tests
[stdout] https://private-anon-ed673324a2-customatepublicapi.apiary-mock.com/v1/open_banking_providers?currency=GBP&country=GB GET
[stdout] Response is {
[stdout]   "items": [
[stdout]     {
[stdout]       "provider_id": "mock-payments-gb-redirect",
[stdout]       "logo_url": "https://client-logos.s3-eu-west-1.amazonaws.com/banks/natwest.svg",
[stdout]       "icon_url": "https://client-logos.s3-eu-west-1.amazonaws.com/banks/banks-icons/mock-payments-gb-redirect-icon.svg",
[stdout]       "display_name": "Natwest",
[stdout]       "country": "GB"
[stdout]     }
[stdout]   ]
[stdout] }

**Comment by jamesmcarthur115555** [comment]
Maybe is the mock server not sandbox that is returning the error

**Comment by SBalac** [comment]
Hi James, I have no knowledge of this server:
https://private-anon-ed673324a2-customatepublicapi.apiary-mock.com

**Comment by SBalac** [comment]
Most people use our Sandbox, which is available at https://sandbox-api.gocustomate.com, e.g.
GET https://sandbox-api.gocustomate.com/v1/open_banking_providers?currency=GBP&country=GB
