### ISSUE TITLE
Enum missing from sandbox cant get transaction list to JSON

### ISSUE THREAD

**Issue by jamesmcarthur115555** [customate/java-sdk#2]
In the enum there is a missing type - or sandbox is returing invalid data 

com.fasterxml.jackson.databind.exc.InvalidFormatException: Cannot deserialize value of type `xxxx.enums.TransactionName` from String "DirectDebitToCustomate": not one of the values accepted for Enum class: [MoneyInObFeeAndTax, IncomingTax, DirectDebitToVirtualWallet, OpenBankingToWallet, MoneyInCcFeeAndTax, DirectDebitToWallet, Refund, MoneyOutBtFeeAndTax, DirectDebitToInternal, LockTransferAndFeeAmount, IncomingFee, IncomingInternal, Release, OutgoingInternal, External, LockFeeAmount, MoneyInDdFeeAndTax, IncomingContribution, VirtualWalletToWallet, CreditCardToWallet, WalletToVirtualWallet, WalletToIban, IncomingDirectDebit, CreditCardToVirtualWallet, MoneyInBtFeeAndTax, InternalFeeAndTax, IbanToWallet]

**Comment by jamesmcarthur115555** [comment]
Also IncomingBankTransfer

**Comment by SBalac** [comment]
This has been fixed. The SDK was returning TransactionName and PaymentScenario values that were internal to our payment API and now returns user-friendly values that are returned to the API user.

**Comment by SBalac** [comment]
PS  DirectDebitToCustomate  doesn't exist as a variable or constant in our systems.
